#!/usr/bin/env python3
"""
Run STS test framework CLI once per data model (sequential by default).

Usage (from project root):
    python scripts/run_autogenerated_tests.py
    STS_BASE_URL=https://sts-qa.cancer.gov/v2 python scripts/run_autogenerated_tests.py

Environment variables:
    STS_PARALLEL_WORKERS  Max models to run concurrently (default: 1 sequential; set to 2, 8, etc. for parallel).
    STS_MODELS            Comma-separated model handles to run (default: all).
    STS_BASE_URL          STS v2 API root (default: https://sts-qa.cancer.gov/v2).
    AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
                          If all three are set, parser_agent runs on the autogenerated log after all models.

Reports are written to reports/<model>/report_<timestamp>.html (and .json).
Exits with 1 if any model run fails.
"""
import io
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

# Allow `python scripts/run_autogenerated_tests.py` from repo root without editable install
_repo_root = Path(__file__).resolve().parent.parent
_src = _repo_root / "src"
if _src.is_dir():
    src_str = str(_src)
    if src_str not in sys.path:
        sys.path.insert(0, src_str)

from sts_test_framework.config import sts_base_url

# Default list of data models to test
DEFAULT_MODELS = [
    "CDS",
    "CCDI",
    "CCDI-DCC",
    "ICDC",
    "CTDC",
    "C3DC",
    "PSDC",
    "mCODE",
    "PDC",
    "CRDC",
    "CRDCSearch",
    "CRDCSubmission"
]

REPORT_BASE = "reports"

DEFAULT_WORKERS = 1


def _parse_workers() -> int:
    raw = os.getenv("STS_PARALLEL_WORKERS", "")
    if not raw.strip():
        return DEFAULT_WORKERS
    try:
        n = int(raw)
        return max(n, 1)
    except ValueError:
        return DEFAULT_WORKERS


def _run_model(
    model: str, base_url: str, project_root: Path
) -> tuple[str, int, str, str, float]:
    """Run the CLI for one model and return (model, returncode, stdout, stderr, elapsed_s)."""
    report_dir = str(Path(REPORT_BASE) / model)
    start = time.monotonic()
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "sts_test_framework.cli",
            "--base-url",
            base_url,
            "--report",
            report_dir,
            "--model",
            model,
            "--release",
            "--quiet",
        ],
        cwd=project_root,
        env=os.environ,
        capture_output=True,
        text=True,
    )
    elapsed = time.monotonic() - start
    return model, result.returncode, result.stdout, result.stderr, elapsed


def _log_and_print(log_buffer: io.StringIO, msg: str, *, file=None, flush: bool = False) -> None:
    """Print to console and append to log buffer."""
    print(msg, file=file, flush=flush)
    log_buffer.write(msg + "\n")


def _parser_agent_env_ok() -> bool:
    return all(
        (os.getenv(k) or "").strip()
        for k in (
            "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY",
            "AWS_REGION",
        )
    )


def _parser_agent_preamble() -> None:
    name = "run_autogenerated_tests.py"
    if not _parser_agent_env_ok():
        print(
            f"{name}: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_REGION are not all set.",
            file=sys.stderr,
        )
        print(
            "  Optional parser agent will be skipped. Export all three (and install boto3) "
            "to enable Bedrock summaries.",
            file=sys.stderr,
        )
    else:
        print(
            f"{name}: AWS credentials set; parser agent will run after autogenerated model "
            "runs if failures are detected.",
            flush=True,
        )


def _run_parser_agent(log_path: Path) -> None:
    if not _parser_agent_env_ok():
        return
    agent_main = _repo_root / "parser_agent" / "main.py"
    if agent_main.is_file():
        subprocess.run(
            [sys.executable, str(agent_main), str(log_path)],
            cwd=_repo_root,
            check=False,
        )


def main() -> None:
    _parser_agent_preamble()

    models_env = os.getenv("STS_MODELS")
    if models_env:
        model_list = [m.strip() for m in models_env.split(",") if m.strip()]
    else:
        model_list = DEFAULT_MODELS

    base_url = sts_base_url()
    project_root = Path(__file__).resolve().parent.parent
    max_workers = _parse_workers()

    log_dir = project_root / "logs"
    log_dir.mkdir(exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%S")
    log_path = log_dir / f"autogenerated_{ts}.log"

    log_buffer = io.StringIO()
    log = lambda msg, **kw: _log_and_print(log_buffer, msg, **kw)

    log(
        f"Running {len(model_list)} model(s) with up to {max_workers} parallel worker(s)",
        flush=True,
    )
    log(f"STS_BASE_URL: {base_url}", flush=True)
    log("", flush=True)

    wall_start = time.monotonic()
    failed: list[str] = []
    results_summary: list[tuple[str, int, float]] = []

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {
            pool.submit(_run_model, model, base_url, project_root): model
            for model in model_list
        }
        for future in as_completed(futures):
            model, returncode, stdout, stderr, elapsed = future.result()
            results_summary.append((model, returncode, elapsed))

            if stdout:
                log_buffer.write(stdout)
            if stderr:
                log_buffer.write(stderr)

            elapsed_str = f"{elapsed:.1f}s"
            if returncode == 0:
                result_line = stdout.strip().splitlines()[-1] if stdout.strip() else ""
                log(f"  [PASS] {model} ({elapsed_str}) {result_line}", flush=True)
            else:
                failed.append(model)
                log(f"  [FAIL] {model} ({elapsed_str})", flush=True)
                if stdout.strip():
                    for line in stdout.strip().splitlines():
                        log(f"         {line}")
                if stderr.strip():
                    for line in stderr.strip().splitlines():
                        log(f"         {line}", file=sys.stderr)

    wall_elapsed = time.monotonic() - wall_start

    log("")
    log(f"--- Summary: {len(model_list)} model(s), wall time {wall_elapsed:.1f}s ---")
    for model, rc, elapsed in sorted(results_summary, key=lambda x: x[0]):
        status = "PASS" if rc == 0 else "FAIL"
        log(f"  {status}  {model} ({elapsed:.1f}s)")

    if failed:
        log(f"\nFailed models: {', '.join(sorted(failed))}", file=sys.stderr)

    if not failed:
        log("\nAll models completed successfully.", flush=True)

    log_path.write_text(log_buffer.getvalue())
    _run_parser_agent(log_path)

    if failed:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
