#!/usr/bin/env bash
# Run the three main report pipelines in sequence (always runs all three).
# Prints per-stage pass/fail and a final summary; exits 1 if any stage failed.
# Order: manual pytest + HTML, then OpenAPI functional suite per model, then term-verify.
# No arguments are forwarded; use each script alone for -m nullcde, STS_MODELS, --warn-only, etc.
#
# Usage (from project root):
#   bash scripts/run_full_suite.sh
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=parser_agent_hook.sh
source "$_SCRIPT_DIR/parser_agent_hook.sh"
parser_agent_print_preamble "run_full_suite.sh" "after all suite stages"

mkdir -p logs
LOGFILE="logs/full_suite_$(date +%Y-%m-%dT%H-%M-%S).log"

failures=()

run_stage() {
  local label=$1
  shift
  echo "=== $label ==="
  "$@"
  local ec=$?
  if [ "$ec" -eq 0 ]; then
    echo ">>> Result: PASSED"
  else
    echo ">>> Result: FAILED (exit $ec)" >&2
    failures+=("$label")
  fi
  echo
}

exec > >(tee "$LOGFILE") 2>&1

run_stage "1/3 run_manual_tests.sh (manual pytest + pytest-html)" bash scripts/run_manual_tests.sh
run_stage "2/3 run_autogenerated_tests.py (CLI per model, HTML + JSON)" python3 scripts/run_autogenerated_tests.py
run_stage "3/3 run_all_term_verify.sh (all term_verify scripts)" bash scripts/run_all_term_verify.sh

echo "=== Full suite summary ==="
if [ "${#failures[@]}" -eq 0 ]; then
  echo "All stages passed."
else
  echo "Failed stage(s):" >&2
  printf '  - %s\n' "${failures[@]}" >&2
fi

parser_agent_run_if_ok "$REPO_ROOT" "$LOGFILE"

if [ "${#failures[@]}" -gt 0 ]; then
  exit 1
fi
exit 0
