#!/usr/bin/env python3
"""
Run STS test framework CLI once per data model (parallel by default).

Usage (from project root):
    python scripts/run_autogenerated_tests.py
    STS_BASE_URL=https://sts-qa.cancer.gov/v2 python scripts/run_autogenerated_tests.py

Environment variables:
    STS_PARALLEL_WORKERS  Max models to run concurrently (default: 4, set to 1 for sequential).
    STS_MODELS            Comma-separated model handles to run (default: all).
    STS_BASE_URL          STS v2 API root (default: https://sts-qa.cancer.gov/v2).

Reports are written to reports/<model>/report_<timestamp>.html (and .json).
Exits with 1 if any model run fails.
"""
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

# Allow `python scripts/run_autogenerated_tests.py` from repo root without editable install
_repo_root = Path(__file__).resolve().parent.parent
_src = _repo_root / "src"
if _src.is_dir():
    src_str = str(_src)
    if src_str not in sys.path:
        sys.path.insert(0, src_str)

from sts_test_framework.config import sts_base_url

# Default list of data models to test
DEFAULT_MODELS = [
    "CDS",
    "CCDI",
    "CCDI-DCC",
    "ICDC",
    "CTDC",
    "C3DC",
    "PSDC",
    "mCODE",
    "PDC",
    "CRDC",
    "CRDCSearch",
    "CRDCSubmission"
]

REPORT_BASE = "reports"

DEFAULT_WORKERS = 4


def _parse_workers() -> int:
    raw = os.getenv("STS_PARALLEL_WORKERS", "")
    if not raw.strip():
        return DEFAULT_WORKERS
    try:
        n = int(raw)
        return max(n, 1)
    except ValueError:
        return DEFAULT_WORKERS


def _run_model(
    model: str, base_url: str, project_root: Path
) -> tuple[str, int, str, str, float]:
    """Run the CLI for one model and return (model, returncode, stdout, stderr, elapsed_s)."""
    report_dir = str(Path(REPORT_BASE) / model)
    start = time.monotonic()
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "sts_test_framework.cli",
            "--base-url",
            base_url,
            "--report",
            report_dir,
            "--model",
            model,
            "--release",
            "--quiet",
        ],
        cwd=project_root,
        env=os.environ,
        capture_output=True,
        text=True,
    )
    elapsed = time.monotonic() - start
    return model, result.returncode, result.stdout, result.stderr, elapsed


def main() -> None:
    models_env = os.getenv("STS_MODELS")
    if models_env:
        model_list = [m.strip() for m in models_env.split(",") if m.strip()]
    else:
        model_list = DEFAULT_MODELS

    base_url = sts_base_url()
    project_root = Path(__file__).resolve().parent.parent
    max_workers = _parse_workers()

    print(
        f"Running {len(model_list)} model(s) with up to {max_workers} parallel worker(s)",
        flush=True,
    )
    print(f"STS_BASE_URL: {base_url}", flush=True)
    print(flush=True)

    wall_start = time.monotonic()
    failed: list[str] = []
    results_summary: list[tuple[str, int, float]] = []

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {
            pool.submit(_run_model, model, base_url, project_root): model
            for model in model_list
        }
        for future in as_completed(futures):
            model, returncode, stdout, stderr, elapsed = future.result()
            results_summary.append((model, returncode, elapsed))

            elapsed_str = f"{elapsed:.1f}s"
            if returncode == 0:
                result_line = stdout.strip().splitlines()[-1] if stdout.strip() else ""
                print(f"  [PASS] {model} ({elapsed_str}) {result_line}", flush=True)
            else:
                failed.append(model)
                print(f"  [FAIL] {model} ({elapsed_str})", flush=True)
                if stdout.strip():
                    for line in stdout.strip().splitlines():
                        print(f"         {line}")
                if stderr.strip():
                    for line in stderr.strip().splitlines():
                        print(f"         {line}", file=sys.stderr)

    wall_elapsed = time.monotonic() - wall_start

    print()
    print(f"--- Summary: {len(model_list)} model(s), wall time {wall_elapsed:.1f}s ---")
    for model, rc, elapsed in sorted(results_summary, key=lambda x: x[0]):
        status = "PASS" if rc == 0 else "FAIL"
        print(f"  {status}  {model} ({elapsed:.1f}s)")

    if failed:
        print(f"\nFailed models: {', '.join(sorted(failed))}", file=sys.stderr)
        sys.exit(1)
    print("\nAll models completed successfully.", flush=True)
    sys.exit(0)


if __name__ == "__main__":
    main()
