"""Scan a log file for test-failure indicators across all script output formats.

Supports:
  - pytest output (FAILED, AssertionError tracebacks)
  - OpenAPI CLI / autogenerated runner ([FAIL], [Fail])
  - run_full_suite.sh stage results (>>> Result: FAILED)
  - term-verify summary lines (FAILED:)
"""

import re
from dataclasses import dataclass, field
from pathlib import Path

CONTEXT_LINES = 3

FAILURE_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"^FAILED\s", re.MULTILINE),
    re.compile(r"\[FAIL\]", re.IGNORECASE),
    re.compile(r">>> Result: FAILED"),
    re.compile(r"^\s*FAILED:", re.MULTILINE),
    # term-verify / run_all_term_verify.sh inner wrapper (output is tee'd; "FAILED:" summary lines may be appended later)
    re.compile(r"finished \(FAILED\)"),
    re.compile(r"AssertionError"),
    re.compile(r"pytest\.fail\("),
    re.compile(r"xargs exited with [1-9]"),
]


@dataclass
class FailureMatch:
    line_number: int
    line: str
    context_before: list[str] = field(default_factory=list)
    context_after: list[str] = field(default_factory=list)

    def as_block(self) -> str:
        parts: list[str] = []
        for ctx in self.context_before:
            parts.append(f"  {ctx}")
        parts.append(f"> {self.line}")
        for ctx in self.context_after:
            parts.append(f"  {ctx}")
        return "\n".join(parts)


@dataclass
class DetectionResult:
    has_failures: bool
    matches: list[FailureMatch] = field(default_factory=list)
    log_content: str = ""


def detect_failures(log_path: str | Path) -> DetectionResult:
    """Read *log_path* and return detection results."""
    path = Path(log_path)
    if not path.is_file():
        return DetectionResult(has_failures=False)

    content = path.read_text(errors="replace")
    lines = content.splitlines()
    matched_line_numbers: set[int] = set()
    matches: list[FailureMatch] = []

    for idx, line in enumerate(lines):
        for pattern in FAILURE_PATTERNS:
            if pattern.search(line):
                if idx not in matched_line_numbers:
                    matched_line_numbers.add(idx)
                    start = max(0, idx - CONTEXT_LINES)
                    end = min(len(lines), idx + CONTEXT_LINES + 1)
                    matches.append(
                        FailureMatch(
                            line_number=idx + 1,
                            line=line,
                            context_before=lines[start:idx],
                            context_after=lines[idx + 1 : end],
                        )
                    )
                break

    return DetectionResult(
        has_failures=len(matches) > 0,
        matches=matches,
        log_content=content,
    )
