"""
STS Test Runner - Flask backend.

Routes:
  GET  /                   Serve the UI
  POST /run                Start a test run; returns {"run_id": "..."}
  GET  /stream/<run_id>    SSE stream of stdout/stderr lines + final exit event
  POST /stop/<run_id>      Kill the running subprocess
  GET  /status             Current run state (idle | running | done)
"""
from __future__ import annotations

import json
import os
import queue
import signal
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path

from flask import Flask, Response, jsonify, render_template, request

PROJECT_ROOT = Path(__file__).resolve().parent.parent

ENVIRONMENTS: dict[str, str] = {
    "qa": "https://sts-qa.cancer.gov/v2",
    "stage": "https://sts-stage.cancer.gov/v2",
    "prod": "https://sts.cancer.gov/v2",
}

SUITES: dict[str, list[str]] = {
    "full": ["bash", "scripts/run_full_suite.sh"],
    "manual": ["bash", "scripts/run_manual_tests.sh"],
    "autogenerated": [sys.executable, "scripts/run_autogenerated_tests.py"],
    "term_verify": ["bash", "scripts/run_all_term_verify.sh"],
    "perf": ["bash", "scripts/run_perf_tests.sh"],
}

# Full-suite stage markers emitted by run_full_suite.sh
FULL_SUITE_STAGE_RE = ["=== 1/3", "=== 2/3", "=== 3/3"]

app = Flask(__name__)

# Global state for the one-at-a-time run model
_state: dict = {
    "run_id": None,
    "status": "idle",          # idle | running | done
    "exit_code": None,
    "suite": None,
    "env": None,
    "started_at": None,
    "finished_at": None,
    "process": None,           # subprocess.Popen | None
    "output_queue": None,      # queue.Queue | None
    "stage": 0,                # 0-3 for full suite progress
    "lock": threading.Lock(),
}


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/status")
def status():
    with _state["lock"]:
        elapsed = None
        if _state["started_at"] is not None:
            end = _state["finished_at"] or time.time()
            elapsed = round(end - _state["started_at"], 1)
        return jsonify({
            "status": _state["status"],
            "run_id": _state["run_id"],
            "exit_code": _state["exit_code"],
            "suite": _state["suite"],
            "env": _state["env"],
            "elapsed": elapsed,
            "stage": _state["stage"],
        })


@app.route("/run", methods=["POST"])
def run():
    body = request.get_json(force=True, silent=True) or {}
    env_key = body.get("env", "qa")
    suite_key = body.get("suite", "full")

    if env_key not in ENVIRONMENTS:
        return jsonify({"error": f"Unknown environment: {env_key}"}), 400
    if suite_key not in SUITES:
        return jsonify({"error": f"Unknown suite: {suite_key}"}), 400

    with _state["lock"]:
        if _state["status"] == "running":
            return jsonify({"error": "A run is already in progress"}), 409

        run_id = str(uuid.uuid4())
        base_url = ENVIRONMENTS[env_key]
        cmd = SUITES[suite_key]

        env = os.environ.copy()
        env["STS_BASE_URL"] = base_url
        # Make sure the src package is importable for python scripts
        src_path = str(PROJECT_ROOT / "src")
        existing = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = f"{src_path}:{existing}" if existing else src_path

        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=str(PROJECT_ROOT),
            env=env,
            text=True,
            bufsize=1,
            # Run in its own process group so we can kill the entire tree
            # (bash -> pytest / python child processes) on stop.
            start_new_session=True,
        )

        q: queue.Queue[str | None] = queue.Queue()

        _state.update({
            "run_id": run_id,
            "status": "running",
            "exit_code": None,
            "suite": suite_key,
            "env": env_key,
            "started_at": time.time(),
            "finished_at": None,
            "process": process,
            "output_queue": q,
            "stage": 0,
        })

    # Read subprocess output in a background thread
    threading.Thread(
        target=_drain_process,
        args=(process, q, run_id, suite_key),
        daemon=True,
    ).start()

    return jsonify({"run_id": run_id})


@app.route("/stream/<run_id>")
def stream(run_id: str):
    """SSE endpoint. Streams log lines then a final 'done' event."""
    def generate():
        with _state["lock"]:
            current_id = _state["run_id"]
            q = _state["output_queue"]

        if current_id != run_id or q is None:
            # Send a synthetic done event for stale run IDs
            yield _sse_event("done", json.dumps({"exit_code": None, "stale": True}))
            return

        while True:
            try:
                item = q.get(timeout=30)
            except queue.Empty:
                # Keep-alive comment to prevent proxy timeouts
                yield ": keep-alive\n\n"
                continue

            if item is None:
                # Sentinel: process finished
                with _state["lock"]:
                    ec = _state["exit_code"]
                    stage = _state["stage"]
                yield _sse_event("done", json.dumps({"exit_code": ec, "stage": stage}))
                return

            # item is a log line
            yield _sse_event("log", json.dumps({"line": item}))

    return Response(generate(), mimetype="text/event-stream",
                    headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@app.route("/stop/<run_id>", methods=["POST"])
def stop(run_id: str):
    with _state["lock"]:
        if _state["run_id"] != run_id:
            return jsonify({"error": "Run ID not found"}), 404
        process = _state["process"]
        if process is None or _state["status"] != "running":
            return jsonify({"error": "No active process"}), 409

    try:
        # Kill the entire process group (catches bash + any child pytest/python processes)
        pgid = os.getpgid(process.pid)
        os.killpg(pgid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        # Process already exited
        pass
    except Exception:
        try:
            process.terminate()
        except Exception:
            pass

    return jsonify({"ok": True})


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _drain_process(process: subprocess.Popen, q: queue.Queue, run_id: str, suite_key: str):
    """Read lines from the process and put them on the queue. Put None when done."""
    stage = 0
    try:
        for line in process.stdout:  # type: ignore[union-attr]
            line = line.rstrip("\n")

            # Track full-suite stage markers for progress
            if suite_key == "full":
                for i, marker in enumerate(FULL_SUITE_STAGE_RE, start=1):
                    if marker in line:
                        stage = i
                        with _state["lock"]:
                            _state["stage"] = stage

            q.put(line)
    finally:
        process.wait()
        exit_code = process.returncode
        with _state["lock"]:
            if _state["run_id"] == run_id:
                _state["status"] = "done"
                _state["exit_code"] = exit_code
                _state["finished_at"] = time.time()
                _state["process"] = None
        q.put(None)  # sentinel


def _sse_event(event: str, data: str) -> str:
    return f"event: {event}\ndata: {data}\n\n"
